name: pragma_prueba
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_localizations: 
    sdk: flutter
  get: ^4.6.6
  get_it: ^7.7.0
  internet_connection_checker: ^1.0.0+1
  logger:
  

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/genius_cat.gif
    - assets/images/low_intelligence.gif
